version: '1'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - app-tier
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  namenode:
    image: apache/hadoop:3.3.5
    hostname: namenode
    command: [ "hdfs", "namenode" ]
    ports:
      - 9870:9870
    env_file:
      - config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    image: apache/hadoop:3
    command: [ "hdfs", "datanode" ]
    env_file:
      - config
  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: apache/hadoop:3
    command: [ "yarn", "nodemanager" ]
    env_file:
      - config
  hive:
    image: apache/hive:3.1.3
    environment:
      HIVE_METASTORE: mysql
      HIVE_SERVER2_THRIFT_BIND_HOST: 0.0.0.0
      HIVE_SERVER2_THRIFT_PORT: 10000
      HIVE_METASTORE_JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:mysql://localhost:3306/hive?createDatabaseIfNotExist=true&amp;useSSL=false
      HIVE_METASTORE_JDBC_USER: root
      HIVE_METASTORE_JDBC_PASSWORD: 123456
      SERVICE_NAME: metastore
    volumes:
      - /path/to/mysql-connector-java.jar:/opt/hive/lib/mysql-connector-java.jar
networks:
  app-tier:
    driver: bridge
